### ISSUE TITLE
help

### ISSUE THREAD

**Issue by GitHubHengheng** [jonomango/nohv#2]
Hello, may I ask after I use the loading vt, the target process detected the direct blue screen, blue screen code is 0x139, I should start from what to analyze this problem?
I mainly just don't know how to start. I tried to analyze the driver file, but there were a lot of instructions and obfuscated code.
If you see a message, give me a little hint. thank you.

**Comment by invlpg** [comment]
https://github.com/jonomango/hv/issues/48
